language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121

script:
  - dotnet restore
  - dotnet build src/Kraken/project.json
  - dotnet build test/Kraken.Tests/project.json
  - cd test/Kraken.Tests && dotnet test && cd ../..
  - dotnet build -c Release src/Kraken/project.json
  - dotnet publish -c Release src/Kraken/project.json