language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0

script:
  - dotnet restore
  - dotnet build
  - cd test/Kraken.Net.Tests
  - dotnet test
  - cd ../..
  - dotnet build -c Release src/Kraken.Net/Kraken.Net.csproj
  - dotnet publish -c Release src/Kraken.Net/Kraken.Net.csproj